[[plugins]]
repo = 'Shougo/dein.vim'


# Snips
[[plugins]]
repo = 'SirVer/ultisnips'
hook_add = '''
    let g:UltiSnipsExpandTrigger="<tab>"
    let g:UltiSnipsJumpForwardTrigger="<tab>"
    let g:UltiSnipsJumpBackwardTrigger="<c-b>"
    let g:UltiSnipsEditSplit="vertical"
'''
[[plugins]]
repo = 'honza/vim-snippets'


# Vim-Session
[[plugins]]
repo = 'xolox/vim-misc'
[[plugins]]
repo = 'xolox/vim-session'
depends = ['vim-misc']
hook_add = '''
    let g:session_directory = '~/.vim/session'
    let g:session_autoload = 'no'
    let g:session_autosave = 'no'
    let g:session_command_aliases = 1
'''


# Git
[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
    let g:gitgutter_max_signs = 200
    highlight GitGutterAdd ctermfg=green
    highlight GitGutterChange ctermfg=yellow
    highlight GitGutterDelete ctermfg=red
    highlight GitGutterChangeDelete ctermfg=yellow
'''

# fugitive bridge to github
[[plugin]]
repo = 'tpope/vim-rhubarb'


# Utils
[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
    let g:NERDTreeShowHidden = 1 " 不可視ファイルを表示する
'''
[[plugins]]
repo = 'jistr/vim-nerdtree-tabs'
[[plugins]]
repo = 'bronson/vim-trailing-whitespace'
hook_add = '''
    autocmd BufWritePre * :FixWhitespace
'''
[[plugins]]
repo = 'tpope/vim-endwise'
[[plugins]]
repo = 'Townk/vim-autoclose'
[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = '''
    let g:indentLine_color_term = 244
'''
[[plugins]]
repo = 'tpope/vim-commentary'
[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'majutsushi/tagbar'
hook_add = '''
    let g:tagbar_autofocus = 1
    let g:tagbar_type_ruby = {
        \ 'kinds' : [
            \ 'm:modules',
            \ 'c:classes',
            \ 'd:describes',
            \ 'C:contexts',
            \ 'f:methods',
            \ 'F:singleton methods'
        \ ]
    \ }
'''
[[plugins]]
repo = 'simeji/winresizer'

# Async plugins
[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
    let g:ale_linters = {} " Exec linters
'''
[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'ludwig/split-manpage.vim'


