[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
    let g:NERDTreeShowHidden = 1 " 不可視ファイルを表示する
'''

[[plugins]]
repo = 'SirVer/ultisnips'

[[plugins]]
repo = 'fatih/vim-go'
hook_add = '''
    let g:go_fmt_command = 'goimports'
    let g:go_fmt_autosave = 1

    let g:go_snippet_engine = 'ultisnips'

    let g:go_highlight_function_calls = 1
    let g:go_highlight_types = 1
'''

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
    let g:gitgutter_max_signs = 200
'''

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'
hook_add = '''
    autocmd BufWritePre * :FixWhitespace
'''

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'Townk/vim-autoclose'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'jwalton512/vim-blade'
