[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'SirVer/ultisnips'

[[plugins]]
repo = 'fatih/vim-go'
hook_add = '''
    let g:go_fmt_command = 'goimports'
    let g:go_highlight_function_calls = 1
    let g:go_fmt_autosave = 1
'''

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'Townk/vim-autoclose'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'jwalton512/vim-blade'
