[[plugins]]
repo = 'Shougo/dein.vim'


# Snips
[[plugins]]
repo = 'SirVer/ultisnips'
[[plugins]]
repo = 'honza/vim-snippets'


# vim
[[plugins]]
repo = 'fatih/vim-go'
do = 'GoInstallBinaries'
hook_add = '''
    let g:go_fmt_command = 'goimports'
    let g:go_metalinter_autosave = 1
    let g:go_metalinter_autosave_enabled = ['vet', 'golint', 'errcheck']

    let g:go_snippet_engine = 'ultisnips'
    let g:go_auto_type_info = 1 " Exec GoInfo when keyword cursor

    let g:go_highlight_function_calls = 1
    let g:go_highlight_types = 1

    autocmd BufWritePre *.go :GoFmt
'''


# Git
[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
    let g:gitgutter_max_signs = 200
'''
[[plugins]]
repo = 'tpope/vim-fugitive'

# fugitive bridge to github
[[plugin]]
repo = 'tpope/vim-rhubarb'



# Utils
[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
    let g:NERDTreeShowHidden = 1 " 不可視ファイルを表示する
'''
[[plugins]]
repo = 'bronson/vim-trailing-whitespace'
hook_add = '''
    autocmd BufWritePre * :FixWhitespace
'''
[[plugins]]
repo = 'tpope/vim-endwise'
[[plugins]]
repo = 'Townk/vim-autoclose'
[[plugins]]
repo = 'Yggdroot/indentLine'
[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'majutsushi/tagbar'

# async plugin
[[plugins]]
repo = 'w0rp/ale'
[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'


# ****************************************************************************
# Custom bundles
# ****************************************************************************

# many language syntax
[[plugins]]
repo = 'sheerun/vim-polyglot'


# blade
[[plugins]]
repo = 'jwalton512/vim-blade'


# c
[[plugins]]
repo = 'vim-scripts/c.vim'
on_ft = ['c', 'cpp']
[[plugins]]
repo = 'ludwig/split-manpage.vim'


# html
## HTML Bundle
[[plugins]]
repo = 'hail2u/vim-css3-syntax'
[[plugins]]
repo = 'gorodinskiy/vim-coloresque'
[[plugins]]
repo = 'tpope/vim-haml'
[[plugins]]
repo = 'mattn/emmet-vim'


# javascript
## Javascript Bundle
[[plugins]]
repo = 'jelera/vim-javascript-syntax'


# php
## PHP Bundle
[[plugins]]
repo = 'arnaud-lb/vim-php-namespace'


# python
## Python Bundle
[[plugins]]
repo = 'davidhalter/jedi-vim'
[[plugins]]
repo = 'raimon49/requirements.txt.vim'
for = 'requirements'


# ruby
[[plugins]]
repo = 'tpope/vim-rails'
[[plugins]]
repo = 'tpope/vim-rake'
[[plugins]]
repo = 'tpope/vim-projectionist'
[[plugins]]
repo = 'thoughtbot/vim-rspec'
[[plugins]]
repo = 'ecomba/vim-ruby-refactoring'


# rust
# Vim racer
[[plugins]]
repo = 'racer-rust/vim-racer'


# Rust.vim
[[plugins]]
repo = 'rust-lang/rust.vim'


# scala
[[plugins]]
repo = 'ktvoelker/sbt-vim'
if = ''' has('python') '''
[[plugins]]
repo = 'derekwyatt/vim-scala'

