# ****************************************************************************
# Custom bundles
# ****************************************************************************

# blade
[[plugins]]
repo = 'jwalton512/vim-blade'


# c
[[plugins]]
repo = 'vim-scripts/c.vim'
on_ft = ['c', 'cpp']


# go
[[plugins]]
repo = 'fatih/vim-go'
do = 'GoInstallBinaries'
on_ft = ['go']
hook_add = '''
    let g:go_bin_path = $GOPATH.'/bin'
    let g:go_fmt_command = 'goimports'
    let g:go_metalinter_autosave = 1
    let g:go_metalinter_autosave_enabled = ['vet', 'golint', 'errcheck']
    let g:go_jump_to_error = 0

    let g:go_snippet_engine = 'ultisnips'
    let g:go_auto_type_info = 1 " Exec GoInfo when keyword cursor

    let g:go_highlight_function_calls = 1
    let g:go_highlight_types = 1
    let g:go_highlight_fields = 1
    let g:go_highlight_functions = 1
    let g:go_highlight_methods = 1
    let g:go_highlight_operators = 1
    let g:go_highlight_build_constraints = 1
    let g:go_highlight_structs = 1
    let g:go_highlight_generate_tags = 1
    let g:go_highlight_space_tab_error = 0
    let g:go_highlight_array_whitespace_error = 0
    let g:go_highlight_trailing_whitespace_error = 0
    let g:go_highlight_extra_types = 1

    autocmd BufWritePre *.go :GoFmt
'''


# html
## HTML Bundle
[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = ['css', 'scss', 'sass', 'html', 'vue', 'jsx', 'javascript']
[[plugins]]
repo = 'gorodinskiy/vim-coloresque'
on_ft = ['css', 'scss', 'sass', 'html', 'vue', 'jsx', 'javascript']
[[plugins]]
repo = 'tpope/vim-haml'
on_ft = ['haml']
[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['css', 'scss', 'sass', 'html', 'vue', 'jsx', 'javascript']


# javascript
## Javascript Bundle
[[plugins]]
repo = 'jelera/vim-javascript-syntax'
on_ft = ['javascript']
hook_add = '''
    let g:javascript_enable_domhtmlcss = 1
'''


# php
## PHP Bundle
[[plugins]]
repo = 'arnaud-lb/vim-php-namespace'
on_ft = ['php']


# python
## Python Bundle
[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = ['python']


# ruby
[[plugins]]
repo = 'tpope/vim-rails'
on_ft = ['ruby']
[[plugins]]
repo = 'tpope/vim-rake'
on_ft = ['ruby']
[[plugins]]
repo = 'tpope/vim-projectionist'
on_ft = ['ruby']
[[plugins]]
repo = 'thoughtbot/vim-rspec'
on_ft = ['ruby']
[[plugins]]
repo = 'ecomba/vim-ruby-refactoring'
on_ft = ['ruby']


# rust
[[plugins]]
repo = 'racer-rust/vim-racer'
on_ft = ['rust']
[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = ['rust']


# scala
[[plugins]]
repo = 'ktvoelker/sbt-vim'
if = ''' has('python') '''
on_ft = ['scala']
[[plugins]]
repo = 'derekwyatt/vim-scala'
on_ft = ['scala']


# many language syntax
# !! Put after language libraries
[[plugins]]
repo = 'sheerun/vim-polyglot'
hook_add = '''
    let g:polyglot_disabled = ['python']
'''
