[tools]
node = "lts"
python = "latest"
go = "latest"
ruby = "latest"
java = "latest"
erlang = "latest"
lua = "latest"
terraform = "latest"
uv = "latest"
git = "latest"
tree = "latest"
wget = "latest"
awscli = "latest"
bat = "latest"
direnv = "latest"
fzf = "latest"
gh = "latest"
jq = "latest"
ripgrep = "latest"
yq = "latest"
ecspresso = "latest"
ecschedule = "latest"
swiftlint = "latest"

[hooks]
postinstall = "sh $HOME/dotfiles/link.sh"
